Moving code coverage from codecov package to CI
openedx/frontend-template-application pull request #453
Opened 2022-06-15 12:48 UTC by mamankhan99

Codecov NodeJS Uploader [package](https://www.npmjs.com/package/codecov) is depreciated since version 3.8.3

This PR move the coverage to CI according to the new guidelines and [depreciation](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/) plan of codecov

2022-06-16 16:48 UTC, arbrandes requested changes
Looks good, modulo a minor nitpick.

2022-06-16 16:48 UTC, arbrandes commented on .github/workflows/ci.yml
> +      uses: codecov/codecov-action@v3
Missing newline at EOF.

2022-06-29 09:47 UTC, mamankhan99 commented
@arbrandes waiting for approval to merge this PR.

2022-07-28 10:53 UTC, arbrandes approved these changes
Approved!  Thanks!

2022-07-28 10:54 UTC, merged